# Generated by Django 4.1.5 on 2023-03-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyparlour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='confirm_password',
        ),
    ]
