# Generated by Django 4.1.5 on 2023-03-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyparlour', '0006_alter_user_details_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField(max_length=10)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
