# Generated by Django 4.1.5 on 2023-03-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyparlour', '0008_alter_booking_details_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='Service',
            field=models.CharField(default='Massage', max_length=15),
        ),
    ]
