# Generated by Django 4.1.5 on 2023-03-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyparlour', '0009_booking_details_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Service',
            field=models.CharField(max_length=15),
        ),
    ]
