# Generated by Django 4.1.5 on 2023-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyparlour', '0010_alter_booking_details_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='User_name',
            field=models.CharField(default='dcjh', max_length=50),
        ),
    ]
