# Generated by Django 4.1.5 on 2023-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyparlour', '0011_booking_details_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='User_name',
            field=models.CharField(max_length=50),
        ),
    ]
